services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: films-frontend
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhosts/films.dev.com.conf:/etc/apache2/sites-enabled/films.dev.com.conf
      - ./config/dev/virtualhosts/urls.js:/var/www/html/app/public_html/config/urls.js
    ports:
      - "8081:80"
